### ISSUE TITLE
Backend C++ crash when Mission demo was discovered

### ISSUE THREAD

**Issue by RyanHurst** [mavlink/MAVSDK-Java#10] opened 2019-04-12 21:17 UTC
This was the crash in the terminal running the backend.
```
[03:10:29|Info ] New system on: 127.0.0.1:14580 (udp_connection.cpp:225)
[03:10:29|Debug] Component Autopilot (1) added. (system_impl.cpp:385)
[03:10:29|Debug] MAVLink: info: [logger] file: ./log/2019-04-12/21_10_29.ulg (system_impl.cpp:292)
[03:10:30|Debug] Discovered 1 component(s) (UUID: 5283920058631409231) (system_impl.cpp:548)
[03:10:30|Info ] System discovered [UUID: 5283920058631409231] (connection_initiator.h:61)
backend_bin(1962,0x70000b4d4000) malloc: *** error for object 0x7ff8760015d0: pointer being freed was not allocated
backend_bin(1962,0x70000b4d4000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
This was the crash in logcats
```
2019-04-12 15:11:19.419 29430-29540/? E/AndroidRuntime: FATAL EXCEPTION: grpc-default-executor-6
    Process: io.dronecore.dronecoreclient, PID: 29430
    io.reactivex.exceptions.OnErrorNotImplementedException: UNAVAILABLE: End of stream or IOException
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
        at io.reactivex.internal.operators.flowable.FlowableDistinct$DistinctSubscriber.onError(FlowableDistinct.java:104)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:221)
        at io.reactivex.internal.operators.flowable.FlowableReplay$BoundedReplayBuffer.replay(FlowableReplay.java:860)
        at io.reactivex.internal.operators.flowable.FlowableReplay$ReplaySubscriber.onError(FlowableReplay.java:406)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.error(FlowableCreate.java:288)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:531)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.tryOnError(FlowableCreate.java:481)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:270)
        at io.dronecode_sdk.telemetry.Telemetry$4.onError(Telemetry.java:564)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
        at io.grpc.Status.asRuntimeException(Status.java:532)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434) 
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) 
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) 
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) 
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699) 
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) 
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) 
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) 
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) 
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) 
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) 
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) 
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) 
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

DronecodeSDK commit: 531a55b9c0ac9ea7a2dbaa5b17cd67c3f62316f8
DronecoreCore-Java commit: 249a950bf8dc28f670606a9984192bfa0d2d78f0

**Comment by JonasVautherin** [comment] 2019-11-06 13:49
I think that's outdated now (I couldn't reproduce), so let's close it.

Feel free to re-open if that still happens :+1:.

**Closed by JonasVautherin** 2019-11-06 13:49 UTC
